spring:
  application:
    name: batch-elastic
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/batchdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: batchuser
    password: batchpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.springframework.batch: DEBUG
