server:
  port: 8086

spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://mysql-order:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: orderuser
    password: orderpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

kafka:
  bootstrap-servers: kafka:9092
