server:
  port: 8089

spring:
  application:
    name: event-server
  datasource:
    url: jdbc:mysql://mysql-event:3306/eventdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: eventuser
    password: eventpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

kafka:
  bootstrap-servers: kafka:9092
