server:
  port: 8089

spring:
  application:
    name: push-server
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: push-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
